import { casDoc, readDoc, DEFAULT_ARTIST } from './_lib.mjs';
import { readArtists, mutateArtists } from './_auth.mjs';

/* What each plan gets.

   The fundamentals are in every row: unlimited shows, the
   whole Studio, the lyrics sheet, the gig calendar, the city feed. A free
   artist can run six nights a week forever. What free costs is a 25% cut on
   money that comes through the app, and a ceiling on how many songs are
   featured at once.

   Lyrics were briefly a paid feature and were put back. An audience that gets a
   sing-along at one artist's gig and not the next one learns that MySet is
   unreliable, which costs more than the subscription is worth. Anything the
   ROOM experiences stays free. */

/* The keys are the ids — free / plus / pro — and they never change: storage, the
   Stripe lookup keys, RANK and every PLAN.plan comparison read them. `label` is
   what a PERSON reads, sold as Hobbyist / Bar Star / Rock Star (founder, 2026-09-12). */
export const PLANS = {
  free: {
    label: 'Hobbyist', price: 0,
    /* How many songs can be live to the audience at once. UNLIMITED on every plan
       since 2026-09-13 (the founder: a small setlist must never be the reason to
       upgrade — the room should feel it has lots and lots of options); the
       library's SIZE is the plan line now (`library` below). The machinery for a
       cap stays, reading Infinity as no cap, so a future plan can have one. */
    featured: Infinity,
    /* SHOWS PER CALENDAR MONTH (UTC — see gigMonthOf in _lib.mjs). This is the one
       limit that tracks what MySet actually costs to run: every phone in the room
       polls for the whole gig, so the bill is driven by gigs played, not by artists
       signed up. Capping the free tier on the real cost driver is what makes free
       survivable — a limit on features would punish the wrong people and save
       nothing. Ten a month is a working weekend player; more is a living.

       It was briefly two a week (2026-09-03), went straight back to four a month,
       and was raised to ten on 2026-09-12 — all at the founder's decision, the
       last one so the free tier is genuinely useful to a gigging artist rather than
       a taster. If it ever moves again, the things that move with it are: the plan
       card copy in the Studio (TIER_COPY) and the worst-case note on `audience`
       below. The Live-tab warning, the past-due banner, the refusal message in
       _lifecycle.mjs, the tests and MYSET-MASTER-OVERVIEW.md all read this number
       rather than repeating it (the overview's plan table is generated by
       tools/overview.mjs straight out of this object). */
    gigs: 10,
    /* HOW MANY PHONES CAN BE IN ONE ROOM AT ONCE.

       This is the OTHER half of the cost driver, and until now it was infinite.
       `gigs` bounds how many nights a free artist plays; nothing bounded how many
       people showed up to one of them — so a single night could cost more than a
       year of the subscription, and there was no ceiling on it at all.

       WHAT A PERSON IN THE ROOM COSTS, measured by tools/loadsim.py walking the
       real polling ladder over a 3-hour gig:

           20 people  $0.028/gig   $0.0014 each
          100         $0.159       $0.0016
          500         $1.137       $0.0023
        1,000         $2.759       $0.0028
        5,000        $18.17        $0.0036   <- per-person cost has SATURATED here
       10,000        $36.40        $0.0036

       So the money is survivable. What is not survivable is the READ PATH: every
       poll re-reads the whole audience bag, so 100x the people is 10,000x the
       internal traffic — 50 MB/s of blob reads at 1,000 people and 5.1 GB/s at
       10,000. The room stops working long before the bill does, which is why these
       numbers are set below what MySet can serve rather than at what it can afford.

       RAISING THEM IS GATED ON THE SNAPSHOT FIX (one shared cached room state
       instead of a full read per phone), not on money. Do not raise them first.

       Four numbers, one place. The Studio copy, the plans cards and the tests all
       read these rather than repeating them. `Infinity` means no ceiling and is
       reserved for the founder. */
    /* 50 since 2026-09-13 (the founder: "10 shows for free — up to 50 people
       each"), down from 200. Worst case: 10 gigs x 50 = under a dollar a month. */
    audience: 50,
    /* HOW MANY SONGS THE LIBRARY HOLDS. 100 on the free plan since 2026-09-13
       (the founder: "add up to 100 songs — and show up to 50 to your audience");
       the paid plans keep MAX_LIBRARY. `featured` above is the other half: how
       many of them are live to the room at once. A library already over the line
       keeps every song it has — the cap refuses the NEXT add, never a song. */
    library: 100,
    cut: 0.25,            // platform share of tips and vote sales
    seats: 1,
    pricing: false,       // change free-vote count, pack prices, replay/ask costs
    setlists: false,      // named subsets of the library, one active at a time
    merch: false,         // sell things from the community page (Perry: a Plus feature)
    /* HIDING a fan's post — sold as "hide 1–2 star reviews". Free until 2026-09-13,
       when the founder moved it to Bar Star (decision 0060) and dropped deleting
       for good altogether: a hidden post is off the page at once and can come
       back, which is all the protection a page needs. The old rule — hide free,
       delete paid — is reversed, not refined. */
    moderate: false,
    /* DATA REPORTS — the Money tab's filed nights: fans, votes and tips from every
       show. Paid since 2026-09-13 (the founder: "viewing data is a paid feature").
       Every night is still FILED on every plan; what the plan buys is reading it
       back, so an upgrade finds the whole history waiting. */
    reports: false,
    promote: false,       // list gigs in cities you don't normally play
    analytics: false,     // earnings by venue / night / song
    presskit: false,
    branding: false,      // your colours and logo on the audience pages
  },
  plus: {
    label: 'Bar Star', price: 1000,
    featured: Infinity,
    gigs: Infinity,
    /* The ladder is 25% free / 10% Plus / 2% Pro, so the
       subscription and the transaction fee trade off against each other and a new
       artist never pays a subscription before they have earned anything. Taken as
       a Stripe `application_fee_amount` on a direct charge — see _connect.mjs. */
    cut: 0.10,
    audience: 300,        // a bar with a floor (the founder, 2026-09-13; was 1,000). Worst single night: well under a dollar.
    library: 200,         // "add up to 200 songs" (the founder, 2026-09-13); Rock Star holds MAX_LIBRARY
    seats: 1,
    pricing: true, setlists: true, merch: true, moderate: true, reports: true,
    promote: false, analytics: false, presskit: false, branding: false,
  },
  pro: {
    label: 'Rock Star', price: 2000,
    featured: Infinity,
    gigs: Infinity,
    cut: 0.02,
    /* A theatre or a festival tent. Worst single night: under $7, and less than
       that in practice because the interval widens with the room.

       2,000 AND NOT 3,000, WHICH IS A DELIBERATE CLIMBDOWN. 3,000 was the first
       number here and the arithmetic behind it was wrong: it puts internal read
       traffic at 137 MB/s, nearly three times the busiest room MySet is actually
       known to serve. 2,000 lands at 61 MB/s, which is the same neighbourhood.
       Sell what the app can do, not what the margin could afford. */
    audience: 2000,
    library: 2000,
    seats: 5,
    pricing: true, setlists: true, merch: true, moderate: true, reports: true,
    promote: true, analytics: true, presskit: true, branding: true,
  },
};
/* WHICH OF THOSE FLAGS IS A REAL FEATURE TODAY.

   The rows above describe the ladder we sell. Four of the flags describe things
   that are DESIGNED AND NOT BUILT — there is no code behind `promote`,
   `analytics`, `presskit` or `branding` anywhere in this repo.

   The Studio shows every locked feature rather than hiding it, which was Perry's
   call and is the right one: an artist should be able to see what paying gets
   them. But greying something as "Pro" implies that paying turns it on, and Perry
   is himself comped to Pro — so without this list he would open the Studio, see
   four features presented as his, and find four dead ends. Worse, so would the
   first person who ever pays.

   So a flag in here is shown as "coming", never as "yours", on every plan
   including Pro. Deleting a name from this list is the last step of building the
   feature, not the first — and `test/limits.mjs` asserts that anything NOT in
   here is actually enforced somewhere, so the list cannot rot in the other
   direction either. */
export const NOT_BUILT = ['promote', 'analytics', 'presskit', 'branding'];

/** The most any library holds. The free plan holds fewer (`library` above);
 *  `libraryCap` is the one place that reads which. */
export const MAX_LIBRARY = 2000;
export const libraryCap = (limits) => (limits && Number(limits.library) > 0) ? Number(limits.library) : MAX_LIBRARY;
export const PLAN_KEYS = Object.keys(PLANS);

/** The plan actually in force — a comped period that has run out falls back. */
export function planOf(artist) {
  if (!artist) return 'free';
  const p = PLAN_KEYS.includes(artist.plan) ? artist.plan : 'free';
  if (p === 'free') return 'free';
  if (artist.planUntil && Number(artist.planUntil) < Date.now()) return 'free';
  return p;
}
export const limitsFor = (plan) => PLANS[plan] || PLANS.free;

export async function planForArtist(aid) {
  const reg = await readArtists();
  const artist = reg.byId[aid];
  const plan = planOf(artist);
  return { plan, limits: limitsFor(plan), artist: artist || null };
}

/** Only the founding artist can mint or revoke codes. */
export const isPlatformOwner = (aid) => aid === DEFAULT_ARTIST;
/** May this artist sell merch? ONE answer for the Studio, the checkout and the page —
 *  the founder predates the registry (planForArtist says free for him), so the owner
 *  bypass is load-bearing here exactly as it is for pricing. */
export const merchAllowed = (aid, limits) => isPlatformOwner(aid) || !!(limits && limits.merch === true);
/** May this artist HIDE a fan's post? Bar Star and up since 2026-09-13 (decision
 *  0060). Same owner bypass and the same one-answer rule as merch. */
export const moderateAllowed = (aid, limits) => isPlatformOwner(aid) || !!(limits && limits.moderate === true);
/** May this artist READ the filed nights on the Money tab? Same shape. */
export const reportsAllowed = (aid, limits) => isPlatformOwner(aid) || !!(limits && limits.reports === true);

/* ---------- promo codes ---------- */
const PROMOS = 'promos';
export const emptyPromos = () => ({ v: 1, codes: {} });

export const cleanCode = (v) =>
  String(v || '').toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 24);

export async function readPromos() {
  const { data } = await readDoc(PROMOS, null);
  const d = data || emptyPromos();
  d.codes ||= {};
  return d;
}
export const mutatePromos = (fn) =>
  casDoc(PROMOS, emptyPromos, (d) => { d.codes ||= {}; return fn(d); });

/** Applies a code to an artist. 100% comps the plan outright; anything less is
 *  recorded so a future subscription checkout can discount it — there is no
 *  billing to halve yet, and pretending otherwise would be a lie. */
export async function redeemPromo(aid, rawCode) {
  const code = cleanCode(rawCode);
  if (!code) return { ok: false, error: 'Enter a code' };

  let promo = null, why = null;
  await mutatePromos((d) => {
    const c = d.codes[code];
    if (!c) { why = 'That code isn’t recognised'; return false; }
    if (c.revoked) { why = 'That code has been turned off'; return false; }
    if (c.maxUses && (c.usedBy || []).length >= c.maxUses) { why = 'That code has been used up'; return false; }
    if ((c.usedBy || []).includes(aid)) { why = 'You’ve already used that code'; return false; }
    c.usedBy = [...(c.usedBy || []), aid];
    promo = { plan: c.plan, months: c.months, pct: c.pct };
    return true;
  });
  if (!promo) return { ok: false, error: why || 'Could not apply that code' };

  const until = Date.now() + (promo.months || 12) * 30 * 86400000;
  await mutateArtists((reg) => {
    const a = reg.byId[aid];
    if (!a) return false;
    if (promo.pct >= 100) { a.plan = promo.plan; a.planUntil = until; a.compedBy = code; }
    else { a.discountPct = promo.pct; a.discountCode = code; a.pendingPlan = promo.plan; }
    return true;
  });

  const thanks = promo.pct >= 100 ? await rewardReferrer(aid) : null;
  return {
    ok: true, code, plan: promo.plan, pct: promo.pct, months: promo.months,
    comped: promo.pct >= 100, until: promo.pct >= 100 ? until : null,
    thankedReferrer: thanks,
  };
}

/** One free month to whoever brought them, each time a referral goes paid.
 *  Called from here now and from billing when it exists. */
export async function rewardReferrer(aid) {
  const reg = await readArtists();
  const me = reg.byId[aid];
  const refId = me && me.referredBy;
  if (!refId || !reg.byId[refId]) return null;

  let name = null;
  await mutateArtists((r) => {
    const ref = r.byId[refId];
    const mine = r.byId[aid];
    if (!ref || !mine) return false;
    // don't pay twice for the same referral
    mine.referralPaid = mine.referralPaid || [];
    if (mine.referralPaid.includes('upgrade')) return false;
    mine.referralPaid.push('upgrade');

    const base = Math.max(Date.now(), Number(ref.planUntil) || 0);
    ref.planUntil = base + 30 * 86400000;
    if (planOf(ref) === 'free') ref.plan = 'plus';
    ref.referralMonths = (ref.referralMonths || 0) + 1;
    name = ref.name;
    return true;
  });
  return name;
}
